{
 "title": "finalProject",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "number of comments",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sql6589600",
     "rawSql": "SELECT COUNT(comment_time) FROM sql6589600.realtimedata where datatype= 'facebook1'"
    }
   ]
  },
  {
   "title": "count (distinct commenter_id)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sql6589600",
     "rawSql": "SELECT COUNT(distinct commenter_id) FROM sql6589600.realtimedata where datatype ='facebook1'"
    }
   ]
  },
  {
   "title": "number of comments",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sql6589600",
     "rawSql": "SELECT COUNT(comment_time) FROM sql6589600.realtimedata where datatype= 'facebook2'"
    }
   ]
  },
  {
   "title": "count (distinct commenter_id)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sql6589600",
     "rawSql": "SELECT COUNT(distinct commenter_id) FROM sql6589600.realtimedata where datatype ='facebook2'"
    }
   ]
  },
  {
   "title": "customer",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sql6589600",
     "rawSql": "select count(distinct commenter_id)\nfrom realtimedata \nwhere datatype = 'facebook1' and (comment_text like '%280%' or comment_text like '%290%'); "
    }
   ]
  },
  {
   "title": "rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "sql6589600",
     "rawSql": "select  CONCAT( round((count(distinct flag) /count(distinct commenter_id)) * 100,2),\"%\") as rate from (\nselect commenter_id\n,case when comment_text like '%280%' or comment_text like '%290%' then commenter_id  else null end as flag\nfrom realtimedata \nwhere datatype = 'facebook1' ) as a;"
    }
   ]
  },
  {
   "title": "customer",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sql6589600",
     "rawSql": "select count(distinct commenter_id)\nfrom realtimedata \nwhere datatype = 'facebook2' and (comment_text like '%b1%' or comment_text like '%B1%' or\ncomment_text like '%b2%' or comment_text like '%B2%' or\ncomment_text like '%b4%' or comment_text like '%B4%' or\ncomment_text like '%l1%' or comment_text like '%L1%' or\ncomment_text like '%l2%' or comment_text like '%L2%' or\ncomment_text like '%l4%' or comment_text like '%L4%' or\ncomment_text like '%cl3%' or comment_text like '%CL3%' or comment_text like '%Cl3%' or comment_text like '%cL3%' or\ncomment_text like '%cl6%' or comment_text like '%CL6%' or comment_text like '%Cl6%' or comment_text like '%cL6%' or\ncomment_text like '%BLC4%' or comment_text like '%blc4%' or comment_text like '%Blc4%' or comment_text like '%BLc4%' or\ncomment_text like '%bLc4%' or comment_text like '%bLC4%' or comment_text like '%blC%' or comment_text like '%BlC4%' );"
    }
   ]
  },
  {
   "title": "rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "sql6589600",
     "rawSql": "select  CONCAT( round((count(distinct flag) /count(distinct commenter_id)) * 100,2),\"%\") from (\nselect commenter_id\n,case when (comment_text like '%b1%' or comment_text like '%B1%' or\ncomment_text like '%b2%' or comment_text like '%B2%' or\ncomment_text like '%b4%' or comment_text like '%B4%' or\ncomment_text like '%l1%' or comment_text like '%L1%' or\ncomment_text like '%l2%' or comment_text like '%L2%' or\ncomment_text like '%l4%' or comment_text like '%L4%' or\ncomment_text like '%cl3%' or comment_text like '%CL3%' or comment_text like '%Cl3%' or comment_text like '%cL3%' or\ncomment_text like '%cl6%' or comment_text like '%CL6%' or comment_text like '%Cl6%' or comment_text like '%cL6%' or\ncomment_text like '%BLC4%' or comment_text like '%blc4%' or comment_text like '%Blc4%' or comment_text like '%BLc4%' or\ncomment_text like '%bLc4%' or comment_text like '%bLC4%' or comment_text like '%blC%' or comment_text like '%BlC4%' )\n then commenter_id  else null end as flag\nfrom realtimedata \nwhere datatype = 'facebook2' ) as a; "
    }
   ]
  },
  {
   "title": "Sales",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "sql6589600",
     "rawSql": "select createtime as time ,sum(number ) as sales from(\r\nSelect  commenter_id,datatype,createtime,substr(comment_text,1,4) as pd_code\r\n,case when convert(substr(comment_text,-1,1),SIGNED) = 0 then 1 \r\nelse convert(substr(comment_text,-1,1),SIGNED)  end as number\r\nFrom sql6589600.realtimedata\r\nwhere datatype = 'facebook1' and (comment_text like '%280%' or comment_text like '%290%')\r\n) as a \r\ngroup by createtime;"
    }
   ]
  },
  {
   "title": "Sales",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "dataset": "sql6589600",
     "rawSql": "Select  createtime as time ,-- comment_text , -- count( comment_text)\r\nsum(case when comment_text like '%=%' then \r\n(case when convert(substr(comment_text,-1,1) ,signed) = 0 then 1 else convert(substr(comment_text,-1,1) ,signed) end )\r\nelse 1 end ) as sale\r\nFrom sql6589600.realtimedata\r\nwhere datatype = 'facebook2' and (comment_text like '%b1%' or comment_text like '%B1%' or\r\ncomment_text like '%b2%' or comment_text like '%B2%' or\r\ncomment_text like '%b4%' or comment_text like '%B4%' or\r\ncomment_text like '%l1%' or comment_text like '%L1%' or\r\ncomment_text like '%l2%' or comment_text like '%L2%' or\r\ncomment_text like '%l4%' or comment_text like '%L4%' or\r\ncomment_text like '%cl3%' or comment_text like '%CL3%' or comment_text like '%Cl3%' or comment_text like '%cL3%' or\r\ncomment_text like '%cl6%' or comment_text like '%CL6%' or comment_text like '%Cl6%' or comment_text like '%cL6%' or\r\ncomment_text like '%BLC4%' or comment_text like '%blc4%' or comment_text like '%Blc4%' or comment_text like '%BLc4%' or\r\ncomment_text like '%bLc4%' or comment_text like '%bLC4%' or comment_text like '%blC%' or comment_text like '%BlC4%' )\r\ngroup by createtime;"
    }
   ]
  }
 ]
}